config/routes.rb
Rails.application.routes.draw do

  get '/sponsors/sign_in' => 'sponsors#signin', as: :newer_sponsor_session
  get '/recyclers/sign_in' => 'recyclers#signin', as: :newer_recycler_session
  get '/charities/sign_in' => 'charities#signin', as: :newer_charity_session

  get '/sponsors/sign_up' => 'sponsors#new', as: :newer_sponsor_registration
  get '/recyclers/sign_up' => 'recyclers#new', as: :newer_recycler_registration
  get '/charities/sign_up' => 'charities#new', as: :newer_charity_registration


  get '/grants' => 'grants#index'
  post '/grants' => 'grants#create'
  get '/grants/new' => 'grants#new'
  get '/grants/:grant_id' => 'grants#show'
  # get '/client_token' => 'grants#generate_client_token'
  # get '/grant_transactions_report' => 'grant_transactions_reportts#grant_transactions_report'





  get '/donations' => 'donations#index'
  get '/donations/new' => 'donations#new', as: :new_donation
  post '/donations' => 'donations#create'
  get '/donations/:id' => 'donations#show'

  get '/submissions/review' => 'submissions#review'


#dwolla stuff
  get '/dwolla/home'
  get '/oauth_return' => 'dwolla#oauth_return'
  # post '/dwolla/request_token'


  resources :submissions do
    member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
    end
  end

  resources :votes

  post '/payments' => 'payments#create'
  get '/payments/process_all' => 'payments#process_all_payments', as: :process_all_payments
  get '/payments/process/:submission_id'  => 'payments#process_payment'

  get '/welcome/whywevote' => 'welcome#whywevote', as: :why


  devise_for :recyclers
  devise_for :sponsors
  devise_for :charities

  get '/sponsors/:id' => 'sponsors#show'
  get '/charities/:id' => 'charities#show'
  get '/recyclers/:id' => 'recyclers#show'

  get '/welcome/calculator' => 'welcome#calculator'

  root 'welcome#intro'

end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :logo
  validates_attachment_content_type :logo, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'
  has_many :grants
  has_many :payments, through: :grants
  has_many :submissions, through: :payments
  has_many :recyclers, through: :submissions

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController

  def new
    if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end

  def show
    @sponsor = Sponsor.find(params[:id])
  end


  def sign_up
    @sponsor = Sponsor.new(logo_params)

    if !@sponsor.logo_file_name
      @sponsor.logo = File.new("#{Rails.root}/public/default-logo.jpeg")
    end

    if @sponsor.save
      redirect_to @sponsor
    end
  end

  def signin
     if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end
  private
  def logo_params
    params.require(:sponsor).permit(:logo)
  end




end

app/helpers/sponsor_helper.rb
module SponsorHelper
  def resource_name
    :sponsor
  end

  def resource
    @resource ||=Sponsor.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:sponsor]
  end

end

app/views/sponsors/_sponsor_logo.html.erb
<%= image_tag sponsor.image.url(:display) %>

app/views/sponsors/new.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-3">Sign up as a Sponsor</h4><br>

<%= form_for 'sponsor', url: sponsor_registration_path do |f| %>
  <%= devise_error_messages! %>

<div class="row">
  <div class="input-field col s12">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="input-field col s12">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="input-field col s12">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="input-field col s12">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>
  <div class="center">
    <div>
      <%= f.label :logo %>
      <%= f.file_field :logo %>
    </div>
  </div>
  <div class="center">
    <div class="actions btn waves-effect waves-light green darken-4">
      <%= f.submit "Sign up" %>
    </div>
  </div>
  <% end %>
  <br>
  <div class="lower-links center">
    <%= link_to "Sign in", newer_sponsor_session_path %><br>

    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end -%>
  </div>
</div>

app/views/sponsors/show.html.erb
<div id="sponsor-info" sponsorid="<%= @sponsor.id %>" class="blue-grey-text text-blue-grey-darken-3">
	<br><br>
	<div class="row">
		<div class="center col s12">
		<h4><%= @sponsor.name %></h4>
	 		<%= image_tag @sponsor.logo.url(), class: 'border-sponsor' %>
	 	</div>
	 	<br><br>
	 	<div class="col s12">
		  <p>To date, <%= @sponsor.name %> has submitted 
		  $<%= number_with_precision(@sponsor.grants.sum(:amount), precision: 2) %> in grants.</p>
		  <p>Grants from <%= @sponsor.name %> have funded $<%= number_with_precision(@sponsor.payments.sum(:amount), precision: 2) %> in payments to recyclers.</p>
		 	<% if @sponsor.grants %>
			  Recent grants:
			  <ul>
			    <% @sponsor.grants.each do |grant| %>
			    <li class="lower-links"> -
			      <%= link_to "Grant ##{grant.id}", "/grants/#{grant.id}" %>, created on <%= grant.created_at.strftime("%Y-%m-%d") %> by <%= grant.sponsor.name %> in the amount of $<%= number_with_precision(grant.original_amount, precision: 2) %>.<br>
			  	<% end %>
			  </ul>
	  	<% end %>
	   
		 	<% if current_sponsor %>
			 	<div class="lower-links">
			    <%= link_to "Submit a new grant", grants_new_path %>
			 	</div>
		 	<% end %>
	  </div>
	</div>
</div>

app/views/sponsors/signin.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-3">Sponsor log in</h4>
  <div class="row">
    <%= form_for 'sponsor', url: new_sponsor_session_path do |f| %>
      <div class="input-field col s12">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="input-field col s12">
        <%= f.label :password %><br>
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
  </div>
    <div class="center">
    <% if devise_mapping.rememberable? -%>
      <div class="input-field col s12">
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
      </div>
    <% end -%>
    <br>
    <div class="actions btn waves-effect waves-light green darken-4">
      <%= f.submit "Log in" %><br>
    </div>
  </div>
<% end %>

<div class="lower-links center">
  <br>
  <%= link_to "Sign up as a sponsor", newer_sponsor_registration_path %><br>
  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end -%>
</div>