config/routes.rb
Rails.application.routes.draw do

  get '/sponsors/sign_in' => 'sponsors#signin', as: :newer_sponsor_session
  get '/recyclers/sign_in' => 'recyclers#signin', as: :newer_recycler_session
  get '/charities/sign_in' => 'charities#signin', as: :newer_charity_session

  get '/sponsors/sign_up' => 'sponsors#new', as: :newer_sponsor_registration
  get '/recyclers/sign_up' => 'recyclers#new', as: :newer_recycler_registration
  get '/charities/sign_up' => 'charities#new', as: :newer_charity_registration


  get '/grants' => 'grants#index'
  post '/grants' => 'grants#create'
  get '/grants/new' => 'grants#new'
  get '/grants/:grant_id' => 'grants#show'
  # get '/client_token' => 'grants#generate_client_token'
  # get '/grant_transactions_report' => 'grant_transactions_reportts#grant_transactions_report'





  get '/donations' => 'donations#index'
  get '/donations/new' => 'donations#new', as: :new_donation
  post '/donations' => 'donations#create'
  get '/donations/:id' => 'donations#show'

  get '/submissions/review' => 'submissions#review'


#dwolla stuff
  get '/dwolla/home'
  get '/oauth_return' => 'dwolla#oauth_return'
  # post '/dwolla/request_token'


  resources :submissions do
    member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
    end
  end

  resources :votes

  post '/payments' => 'payments#create'
  get '/payments/process_all' => 'payments#process_all_payments', as: :process_all_payments
  get '/payments/process/:submission_id'  => 'payments#process_payment'

  get '/welcome/whywevote' => 'welcome#whywevote', as: :why


  devise_for :recyclers
  devise_for :sponsors
  devise_for :charities

  get '/sponsors/:id' => 'sponsors#show'
  get '/charities/:id' => 'charities#show'
  get '/recyclers/:id' => 'recyclers#show'

  get '/welcome/calculator' => 'welcome#calculator'

  root 'welcome#intro'

end

app/models/charity.rb
class Charity < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :donations
  has_many :recyclers, through: :donations
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  # def index
  # end
  def new
    if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end

  def signin
    if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end

end

app/helpers/charity_helper.rb
module CharityHelper
  def resource_name
    :charity
  end

  def resource
    @resource ||=Charity.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:charity]
  end

end

app/views/charities/new.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-3">Sign up as a Charity</h4>
<br>
<div class="row">
  <%= form_for 'charity', url: charity_registration_path do |f| %>
  <%= devise_error_messages! %>

    <div class="input-field col s12">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="input-field col s12">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="input-field col s12">
      <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="input-field col s12">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
</div>
  <div class="center">
  <div class="actions btn waves-effect waves-light green darken-4 center">
    <%= f.submit "Sign up", class: 'center' %>
    <% end %>
  </div>
  <br>
  <br>
  <div class="lower-links">
    <%= link_to "Sign in", newer_charity_session_path %><br>
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
    <% end %>
  </div>
</div>

app/views/charities/show.html.erb
<div id="charity-info" name="<%= current_charity.id %>"></div>
<h4 class="blue-grey-text text-blue-grey-darken-3"><%= current_charity.name %></h4>
<p>To date, you've received $<%= current_charity.donations.sum(:amount) %> through <%= current_charity.donations.count %> donations from recyclers!</p>
<!-- style note: need to test this, blank on styling -->
<div>
	The following recyclers have donated to you:
	<% if current_charity.recyclers %>
	  <ul>
	    <% current_charity.recyclers.each do |recycler| %>
	      <li><%= recycler.first_name %> <%= recycler.last_name %></li>
	    <% end %>
	  </ul>
	<% end %>
</div>

app/views/charities/signin.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-3">Log in as a Charity</h4>
<br>
<div class="row">
  <%= form_for 'charity', url: new_charity_session_path do |f| %>
  <div class="input-field col s12">
    <%= f.label :email %><br>
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="input-field col s12">
    <%= f.label :password %><br>
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

</div>
  <div class="center">
  <% if devise_mapping.rememberable? -%>
    <div class="input-field col s12">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>
  <br>

    <div class="actions btn waves-effect waves-light green darken-4">
      <%= f.submit "Log in" %>
    </div>
  <% end %>

  <div class="lower-links">
    <br>
  <%= link_to "Sign up", newer_charity_registration_path %><br>
    <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br /> 
  <% end %>
  </div>
</div>