config/routes.rb
Rails.application.routes.draw do

  get '/sponsors/sign_in' => 'sponsors#signin', as: :newer_sponsor_session
  get '/recyclers/sign_in' => 'recyclers#signin', as: :newer_recycler_session
  get '/charities/sign_in' => 'charities#signin', as: :newer_charity_session

  get '/sponsors/sign_up' => 'sponsors#new', as: :newer_sponsor_registration
  get '/recyclers/sign_up' => 'recyclers#new', as: :newer_recycler_registration
  get '/charities/sign_up' => 'charities#new', as: :newer_charity_registration


  get '/grants' => 'grants#index'
  post '/grants' => 'grants#create'
  get '/grants/new' => 'grants#new'
  get '/grants/:grant_id' => 'grants#show'
  # get '/client_token' => 'grants#generate_client_token'
  # get '/grant_transactions_report' => 'grant_transactions_reportts#grant_transactions_report'





  get '/donations' => 'donations#index'
  get '/donations/new' => 'donations#new', as: :new_donation
  post '/donations' => 'donations#create'
  get '/donations/:id' => 'donations#show'

  get '/submissions/review' => 'submissions#review'


#dwolla stuff
  get '/dwolla/home'
  get '/oauth_return' => 'dwolla#oauth_return'
  # post '/dwolla/request_token'


  resources :submissions do
    member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
    end
  end

  resources :votes

  post '/payments' => 'payments#create'
  get '/payments/process_all' => 'payments#process_all_payments', as: :process_all_payments
  get '/payments/process/:submission_id'  => 'payments#process_payment'

  get '/welcome/whywevote' => 'welcome#whywevote', as: :why


  devise_for :recyclers
  devise_for :sponsors
  devise_for :charities

  get '/sponsors/:id' => 'sponsors#show'
  get '/charities/:id' => 'charities#show'
  get '/recyclers/:id' => 'recyclers#show'

  get '/welcome/calculator' => 'welcome#calculator'

  root 'welcome#intro'

end

app/models/recycler.rb
class Recycler < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions
  has_many :payments, through: :submissions
  has_many :grants, through: :payments
  has_many :sponsors, through: :grants

  has_many :votes, as: :voter

  has_many :donations
  has_many :charities, through: :donations


  def needed_votes
    (self.submissions.count * 3) - self.find_voted_items.count
  end

end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  # def index
  # end

  def show
    @submissions = Submission.where(recycler_id: current_recycler.id)
  end
  def new
    if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end

  def signin
    if recycler_session || charity_session || sponsor_session
      flash[:notice] = 'You are already signed in'
      redirect_to '/'
    end
  end

end

app/helpers/recycler_helper.rb
module RecyclerHelper
  def resource_name
    :recycler
  end

  def resource
    @resource ||=Recycler.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:recycler]
  end

end

app/views/recyclers/new.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-4">Sign up as a Recycler</h4>
<br>
<%= form_for 'recycler', url: recycler_registration_path do |f| %>
  <%= devise_error_messages! %>

  <div class="row">
    <div class="input-field col s12 l12">
      <%= f.label :email %><br>
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="input-field col s12 l6">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>

    <div class="input-field col s12 l6">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

    <div class="input-field col s12 l6">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="input-field col s12 l6">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  </div>
    <div class="center">
      <div class="cactions btn waves-effect waves-light green darken-4">
        <%= f.submit "Sign up" %>
      </div>
<% end %>
    <br><br>
    <div class="lower-links">
    <%= link_to "Already registered? Sign in!", newer_recycler_session_path %>
      <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %><br>
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
      <% end -%>
    </div>
    </div>

app/views/recyclers/show.html.erb
<div id="recycler-info" recyclerid="<%= current_recycler.id %>" class="blue-grey-text text-blue-grey-darken-4">
	<br><br>
	<div class="row">
		<div class="col s12">
			<h4><%= "Welcome #{current_recycler.first_name}!" %></h4>
			<p> To date:</p>
			<p>- You've submitted <%= current_recycler.submissions.count %> collection(s) of recyclables<br>
			- You've received $<%= number_with_precision(current_recycler.funds, precision: 2) %> in payments<br>
			- You've donated $<%= number_with_precision(current_recycler.donations.sum(:amount), precision: 2) %> to charities</p>
		</div>
		<div class="divider"></div>
			<div class="col s12 l12 lower-links center">
				<%= link_to "Submit your recycling", new_submission_path %> |
				<%= link_to "Donate to charity", new_donation_path %>
			</div>
	</div>
	<div class="divider"></div><br>
	<div class="lower-links center">
		<b>Your recycling submissions:</b>
		<% if @submissions %>
		  <ul class="card-panel collection">
		    <% @submissions.each do |sub| %>
		      <li class="collection-item avatar">
		      	<%= image_tag sub.image.url(), class: "circle border-thin" %>
		        <%= link_to "Submission id##{sub.id}", "/submissions/#{sub.id}" %> || Created at <%= sub.created_at.strftime("%Y-%m-%d") %> || Status: <%= sub.status %>
		      </li>
		    <% end %>
		  </ul>
		  <p>Disagree with a submission decision? <a href="mailto:example@example.example">Email us</a>.</p>
		<% end %>
	</div>
</div>

app/views/recyclers/signin.html.erb
<br><br>
<h4 class="blue-grey-text text-blue-grey-darken-3">Log in as a recycler</h4>
<br>
<div class="row">
  <div class="col s12">
    <%= form_for 'recycler', url: new_recycler_session_path do |f| %>
      <div class="input-field col s12">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="input-field col s12">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
  </div>
</div>
  <div class="center">
      <div class="actions btn waves-effect waves-light green darken-4">
        <%= f.submit "Log in" %>
      </div>
      <% if devise_mapping.rememberable? -%>
        <div class="field">
           <br>
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %>
        </div>
      <% end -%>
    <% end %>

    <br>

    <div class="lower-links">
      <%= link_to "Sign up", newer_recycler_registration_path %><br>
      <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
      <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
      <% end -%>
    </div>
  </div>  