config/routes.rb
Rails.application.routes.draw do

  get '/sponsors/sign_in' => 'sponsors#signin', as: :newer_sponsor_session
  get '/recyclers/sign_in' => 'recyclers#signin', as: :newer_recycler_session
  get '/charities/sign_in' => 'charities#signin', as: :newer_charity_session

  get '/sponsors/sign_up' => 'sponsors#new', as: :newer_sponsor_registration
  get '/recyclers/sign_up' => 'recyclers#new', as: :newer_recycler_registration
  get '/charities/sign_up' => 'charities#new', as: :newer_charity_registration


  get '/grants' => 'grants#index'
  post '/grants' => 'grants#create'
  get '/grants/new' => 'grants#new'
  get '/grants/:grant_id' => 'grants#show'
  # get '/client_token' => 'grants#generate_client_token'
  # get '/grant_transactions_report' => 'grant_transactions_reportts#grant_transactions_report'





  get '/donations' => 'donations#index'
  get '/donations/new' => 'donations#new', as: :new_donation
  post '/donations' => 'donations#create'
  get '/donations/:id' => 'donations#show'

  get '/submissions/review' => 'submissions#review'


#dwolla stuff
  get '/dwolla/home'
  get '/oauth_return' => 'dwolla#oauth_return'
  # post '/dwolla/request_token'


  resources :submissions do
    member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
    end
  end

  resources :votes

  post '/payments' => 'payments#create'
  get '/payments/process_all' => 'payments#process_all_payments', as: :process_all_payments
  get '/payments/process/:submission_id'  => 'payments#process_payment'

  get '/welcome/whywevote' => 'welcome#whywevote', as: :why


  devise_for :recyclers
  devise_for :sponsors
  devise_for :charities

  get '/sponsors/:id' => 'sponsors#show'
  get '/charities/:id' => 'charities#show'
  get '/recyclers/:id' => 'recyclers#show'

  get '/welcome/calculator' => 'welcome#calculator'

  root 'welcome#intro'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallChange</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
    <script src="https://js.braintreegateway.com/web/3.0.2/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.0.2/js/hosted-fields.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="green darken-3">
      <div class="navbar fixed container">
        <br>
      </div>
    </div>
    <!-- <div class="page-flexbox-wrapper"> -->
    <nav class="green show-on-large">
    <div class="navbar container show-on-large">
      <a href="/" class="left"><img src="/images/nav_bar_logo.png" height=66 width=180></a>
        <% if current_recycler %>
          <ul id="slide-out" class="side-nav">
            <li>
              <div class="userView">
                <%= link_to "logged in as #{current_recycler.email}", "/recyclers/#{current_recycler.id}", id: "navbarlinks"%>
                <%= link_to "recycle your stuff!", new_submission_path, id: "navbarlinks" %>
                <%= link_to "sign out", destroy_recycler_session_path, method: :delete, id: "navbarlinks" %>
              </div>
            </li>
          </ul>
          <a href="#" data-activates="slide-out" class="button-collapse right"><i class="material-icons">menu</i></a>
        <% elsif current_sponsor %>
          <ul id="slide-out" class="side-nav">
            <li>
              <div class="userView">
                <%= link_to "logged in as #{current_sponsor.email}", "/sponsors/#{current_sponsor.id}", id: "navbarlinks"%>
                <%= link_to "create a grant", grants_new_path, id: "navbarlinks" %>
                <%= link_to "sign out", destroy_sponsor_session_path, method: :delete %>
              </div>
            </li>
          </ul>
          <a href="#" data-activates="slide-out" class="button-collapse right"><i class="material-icons">menu</i></a>
        <% elsif current_charity %>
          <ul id="slide-out" class="side-nav">
            <li>
              <div class="userView">
                <%= link_to "#{current_charity.email}", "/charities/#{current_charity.id}", id: "navbarlinks"%>
                <%= link_to "view your donations", "/charities/#{current_charity.id}", id: "navbarlinks"%>
                <%= link_to "sign out", destroy_charity_session_path, method: :delete %>
              </div>
            </li>
          </ul>
          <a href="#" data-activates="slide-out" class="button-collapse right"><i class="material-icons">menu</i></a>
        <% else %>
          <ul class="right">
            <li><%= link_to "sign up or log in", new_recycler_session_path %></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <main class="container">
      <%= yield %>
    </main>

    <!-- </div> -->
  </body>
  <footer class="page-footer green">
    <div class="row center">
      <div id="grantstotal" class="container center white-text text-white col s6 left ">
        <b>Total grants available: $<%= number_with_precision(GrantsController.total, precision: 2) %></b>
      </div>
      <div id="secondarylogins" class="container green link-white white-text text-white col s6 right">
        <%= link_to "for sponsors", new_sponsor_session_path %> |
        <%= link_to "for charities", new_charity_session_path %>
      </div>
    </div>
    <br>
  </footer>
</html>